Repository elastic/apm-integration-testing, pull requests merged in 2018-11, with the labels that each got.

#214 opbeans-go: honour repo/branch build args
  docker/opbeans/go/Dockerfile
Labels: [zube]: Inbox

#217 add --opbeans-apm-server-secret-token
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: [zube]: In Review

#222 [APM-CI] support to pass a branch, tag, or sha1 commit as a version of the go agent
  docker/go/nethttp/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: automation

#223 [APM-CI] support to pass a branch, tag, or sha1 commit as a version of the java agent
  docker/java/spring/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: automation

#195 docker/go/nethttp: update to go.elastic.co/apm
  docker/go/nethttp/Dockerfile
  docker/go/nethttp/main.go
Labels: [zube]: In Progress
