Repository elastic/apm-integration-testing, pull requests merged in 2019-11, with the labels that each got.

#663 Cache docker images in the workers
  .ci/packer_cache.sh
Labels: automation

#665 cache opbeans-frontend docker image
  .ci/packer_cache.sh
Labels: automation, ci

#667 xpack secure by default
  .ci/scripts/8.0-upgrade.sh
  .ci/scripts/agent.sh
  .ci/scripts/all.sh
  .ci/scripts/dotnet.sh
  .ci/scripts/go.sh
  .ci/scripts/java.sh
  .ci/scripts/nodejs.sh
  .ci/scripts/opbeans.sh
  .ci/scripts/python.sh
  .ci/scripts/ruby.sh
  .ci/scripts/rum.sh
  .ci/scripts/server.sh
  .ci/scripts/unit-tests.sh
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: enhancement

#664 timeouts resistance for the loadgen in the opbeans-rum project
  docker/opbeans/rum/tasks.js
Labels: [zube]: Inbox, automation

#668 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#656 feat: add support to configure TLS on the APM Server
  Makefile
  scripts/modules/apm_agents.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/modules/opbeans.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  scripts/tls/cert.crt
  scripts/tls/key.pem
Labels: automation, enhancement

#637 fix: Filebeat configuration
  docker/filebeat/filebeat.yml
  docker/opbeans/go/Dockerfile
  docker/opbeans/java/Dockerfile
  docker/opbeans/python/Dockerfile
Labels: automation, bug

#672 fix: ELASTIC_APM_VERIFY_SERVER_CERT environment variable in docker-compose
  scripts/modules/apm_agents.py
  scripts/modules/opbeans.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: automation, bug

#673 feat: grab elasticsearch data on fails
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/elasticdump
Labels: automation, ci, enhancement

#674 [apm-ci]: cache docker images
  .ci/packer_cache.sh
Labels: automation
