Repository elastic/apm-integration-testing, pull requests merged in 2019-09, with the labels that each got.

#583 feat: disable shallow cloning when using downstream pipelines
  .ci/integrationTestDownstream.groovy
Labels: automation, ci

#584 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
  .ci/jobs/apm-integration-tests.yml
Labels: automation, ci

#563 feat: update scripts
  .ci/scripts/gren
  .ci/scripts/shellcheck
  .ci/scripts/yamllint
Labels: [zube]: In Review, automation, ci

#586 feat: disable shallow cloning when using downstream pipelines (#583)
  .ci/integrationTestDownstream.groovy
Labels: automation, backport, ci

#585 feat: disable shallow cloning when using downstream pipelines (#583)
  .ci/integrationTestDownstream.groovy
Labels: automation, backport, ci

#587 feat: disable shallow cloning when using downstream pipelines (#583)
  .ci/integrationTestDownstream.groovy
Labels: automation, backport, ci

#590 bump dotnet apm-agent version
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
Labels: automation, enhancement

#579 update apm-server healthcheck url
  docker/apm-server/haproxy/docker-entrypoint.sh
Labels: bug

#592 ci(jenkins): no run when opbeans
  .ci/integrationTestSelector.groovy
Labels: automation, ci

#557 feat: Allow run integration tests against any APM Server and Elasticsearch URL
  Makefile
  conftest.py
  docker/apm-server/Dockerfile
  docker/filebeat/filebeat.simple.yml
  docker/filebeat/filebeat.yml
  docker/heartbeat/heartbeat.yml
  docker/logstash/pipeline/apm.conf
  docker/metricbeat/metricbeat.yml
  scripts/compose.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation, enhancement

#567 add --apm-server-record option
  docker/apm-server/recorder/Dockerfile
  docker/apm-server/recorder/go.mod
  docker/apm-server/recorder/main.go
  docker/apm-server/teeproxy/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: enhancement

#593 feat: add option to set service.enviroment value for opbeans
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: automation, enhancement

#595 fix: fix broken BC download
  scripts/compose.py
Labels: automation, bug

#598 docs: include reference to the QUICKSTART doc in the readme
  README.md
Labels: automation, docs

#599 test: add 5.1 release to the test matrix
  tests/versions/python.yml
Labels: automation, ci

#602 fix: add a call to add_arguments supper method on Kibana, some test to check the missing options
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: automation, bug

#605 fix: ignore opbeans-*01, load OPBEANS_URLS when param is set
  scripts/compose.py
Labels: automation, bug

#606 fix: disable elasticdump
  .ci/integrationTestDownstream.groovy
  conftest.py
  tests/agent/concurrent_requests.py
Labels: automation, bug, ci

#608 fix: set DEFAULT_APM_JS_SERVER_URL to http://localhost:8200
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: automation

#615 chore: add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automation, chore

#614 fix: ignore lint documentation warnings
  Makefile
Labels: automation

#597 refactor: split compose.py into modules
  Makefile
  scripts/compose.py
  scripts/modules/__init__.py
  scripts/modules/apm_agents.py
  scripts/modules/aux_services.py
  scripts/modules/beats.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/modules/helpers.py
  scripts/modules/opbeans.py
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: automation, refactor
