Repository elastic/apm-integration-testing, pull requests merged in 2019-06, with the labels that each got.

#458 enable apm-server ILM by default in 7.2+
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: [zube]: Inbox

#466 add alpine, busybox, and golang:1.12
  .ci/packer_cache.sh
Labels: [zube]: Inbox, automation

#465 (#464) Add support for MBP and JJBB
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/jobs/apm-integration-test-axis-pipeline-mbp-jjbb.yml
  .ci/jobs/apm-integration-tests-mbp-jjbb.yml
  Jenkinsfile
  JenkinsfileAxis
Labels: [zube]: Inbox, automation

#459 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
  JenkinsfileAxis
Labels: [zube]: In Review, automation

#461 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
  JenkinsfileAxis
Labels: [zube]: In Review, automation

#460 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
  JenkinsfileAxis
Labels: [zube]: In Review, automation

#470 ci(jenkins): notify github check of the parent stream, if any
  .ci/Jenkinsfile
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#471 feat: support to build apm server from a particular commit or branch
  docker/apm-server/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation

#477 feat: Increase test coverage for the repo/branch flags of some apm agents
  scripts/tests/service_tests.py
Labels: [zube]: In Review

#478 fix: broken make call
  docker/apm-server/Dockerfile
Labels: automation, ci

#481 fix: SRC was not declared in the multistage build but in the parent one
  docker/apm-server/Dockerfile
Labels: automation, bug

#476 fix: allow to set --no-kibana with the --all option
  scripts/compose.py
Labels: [zube]: In Review, automation, bug

#480 close #482 feat(jenkins): Pipeline test selector
  .ci/Jenkinsfile
  .ci/integrationTestSelector.groovy
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/scripts/agent.sh
  Jenkinsfile
Labels: automation, ci

#484 fix(jjbb): pipeline name
  .ci/jobs/apm-integration-tests-selector-mbp.yml
Labels: automation, bug, ci

#485 fix(jenkins): withEnv causes ClassCastException in the Pipeline
  .ci/integrationTestSelector.groovy
Labels: automation, ci

#486 fix(jenkins): assign a top level node to the pipeline
  .ci/integrationTestSelector.groovy
Labels: automation, ci

#490 fix: signal internal Node.js workload script to disable
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: [zube]: In Review

#497 feat: support apm ruby agent with either branches or sha1s
  docker/ruby/rails/Dockerfile
  docker/ruby/rails/testapp/Gemfile
Labels: automation

#498 fix: test_opbeans_loadgen failed as the dict is not ordered
  scripts/compose.py
Labels: automation

#491 Improve output of Opbeans Node.js entrypoint script
  docker/opbeans/node/entrypoint.sh
Labels: [zube]: In Review

#501 feat: enable build args for the ruby agent
  docker/ruby/rails/Dockerfile
  docker/ruby/rails/run.sh
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: [zube]: Inbox, automation

#493 ci(jenkins): enable unit tests for the integration tests app
  .ci/Jenkinsfile
  Jenkinsfile
Labels: [zube]: Inbox, automation

#503 fix: persist more builds
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/jobs/apm-integration-test-axis-pipeline-mbp-jjbb.yml
  .ci/jobs/apm-integration-test-axis-pipeline.yml
  .ci/jobs/apm-integration-tests-mbp-jjbb.yml
  .ci/jobs/apm-integration-tests-mbp.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/defaults.yml
  .ci/packer_cache.sh
Labels: automation

#504 chore: rename jobs
  .ci/Jenkinsfile
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests.yml
Labels: automation

#506 fix: dict is now ordered by key
  .ci/Jenkinsfile
  .ci/scripts/unit-tests.sh
  Jenkinsfile
  README.md
  scripts/compose.py
Labels: [zube]: In Review, automation

#513 fix: test_opbeans_loadgen as it does require an ordered list
  scripts/compose.py
Labels: automation, ci

#514 ci: add crossbuild docker images
  .ci/packer_cache.sh
Labels: automation

#515 ci: change the stats instance
  .ci/integrationTestDownstream.groovy
  JenkinsfileAxis
Labels: [zube]: In Review, automation

#510 ci(jenkins): use agentMapping step
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  JenkinsfileAxis
Labels: [zube]: In Review, automation, ci

#517 ci: ignore SCM triggers on downstream jobs
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
Labels: automation
