Repository elastic/apm-integration-testing, pull requests merged in 2019-07, with the labels that each got.

#520 fix: property access error
  .ci/integrationTestDownstream.groovy
Labels: automation

#516 feat: enable 8.0.0 version
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/8.0-upgrade.sh
  Jenkinsfile
  JenkinsfileAxis
  scripts/compose.py
Labels: [zube]: In Review, automation

#522 fix(jenkins): steps is required in the context of the class
  JenkinsfileAxis
Labels: automation, ci

#521 ci(jenkins): create upgrade tests pipeline using JJBB
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
Labels: automation, ci

#518 ci(jenkins): enable upgrade tests pipeline
  .ci/integrationTestUpgrade.groovy
Labels: [zube]: In Review, automation

#526 fix: rum-js docker image cannot be built
  docker/rum/Dockerfile
Labels: automation, bug

#524 feat: dotnet agent uses Elastic.Apm.NetCoreAll and enable --opbeans-dotnet-version
  docker/dotnet/aspnetcore/Startup.cs
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
  docker/dotnet/run.sh
  docker/opbeans/dotnet/run.sh
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: automation

#529 feat: dotnet agent uses Elastic.Apm.NetCoreAll and enable --opbeans-dotnet-version
  docker/dotnet/aspnetcore/Startup.cs
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
  docker/dotnet/run.sh
  docker/opbeans/dotnet/run.sh
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: automation, backport

#487 feat: validate docker-compose has been installed as a prerequisite
  README.md
  scripts/compose.py
Labels: [zube]: In Review, enhancement

#530 fix: unexpected U+00A0 character
  scripts/docker-get-logs.sh
Labels: automation, ci

#532 fix: missing dependencies in the rumjs agent
  docker/rum/Dockerfile
  docker/rum/run.sh
Labels: automation, bug

#536 fix: user error step, allow empty junit results
  JenkinsfileAxis
Labels: automation, backport, bug, ci

#537 fix: user error step, allow empty junit results
  .ci/integrationTestDownstream.groovy
  JenkinsfileAxis
Labels: automation, backport, bug, ci

#535 fix: user error step, allow empty junit results
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  JenkinsfileAxis
Labels: automation, bug, ci

#538 fix: user error step, allow empty junit results
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/integrationTestUpgrade.groovy
  JenkinsfileAxis
Labels: automation, backport, bug, ci

#539 fix: set only build to keep setting
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/jobs/defaults.yml
Labels: automation, ci

#541 feat: delete legacy integration testing jobs
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/scripts/all.sh
  .ci/scripts/common.sh
  .ci/scripts/go.sh
  .ci/scripts/java.sh
  .ci/scripts/kibana.sh
  .ci/scripts/nodejs.sh
  .ci/scripts/python.sh
  .ci/scripts/ruby.sh
  .ci/scripts/server.sh
  scripts/ci/versions_nodejs.sh
  scripts/ci/versions_python.sh
  scripts/ci/versions_ruby.sh
Labels: automation, ci

#542 feat: delete legacy integration testing jobs
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/scripts/all.sh
  .ci/scripts/common.sh
  .ci/scripts/go.sh
  .ci/scripts/java.sh
  .ci/scripts/kibana.sh
  .ci/scripts/nodejs.sh
  .ci/scripts/python.sh
  .ci/scripts/ruby.sh
  .ci/scripts/rum.sh
  .ci/scripts/server.sh
  .ci/scripts/unit-tests.sh
  JenkinsfileAxis
Labels: automation, ci

#543 feat: delete legacy integration testing jobs
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/integrationTestUpgrade.groovy
  .ci/jobs/apm-integration-test-axis-pipeline.yml
  .ci/jobs/apm-integration-tests-mbp.yml
  Jenkinsfile
  JenkinsfileAxis
Labels: automation, ci

#540 feat: delete legacy integration testing jobs
  .ci/jobs/apm-integration-test-axis-pipeline.yml
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-mbp.yml
  .ci/jobs/apm-integration-tests.yml
  Jenkinsfile
  JenkinsfileAxis
Labels: automation, ci

#545 [7.x] tests/agent: search on processor.event
  tests/agent/concurrent_requests.py
Labels: backport

#547 feat: pre-commit config
  .ci/.yamlint.yml
  .pre-commit-config.yaml
Labels: automation, enhancement

#546 feat: backport config
  .backportrc.json
Labels: [zube]: In Review, automation, enhancement

#549 [6.x] feat: pre-commit config (#547)
  .ci/.yamlint.yml
  .pre-commit-config.yaml
Labels: [zube]: In Review, automation, backport, enhancement

#550 [6.x-v1] feat: pre-commit config (#547)
  .ci/.yamlint.yml
  .pre-commit-config.yaml
Labels: [zube]: In Review, automation, backport, enhancement

#551 [7.x] feat: pre-commit config (#547)
  .ci/.yamlint.yml
  .pre-commit-config.yaml
Labels: [zube]: In Review, automation, backport, enhancement

#555 ci: enable pre-commit stage
  .ci/Jenkinsfile
  .ci/scripts/shellcheck
  .ci/scripts/validate.sh
  .ci/scripts/yamllint
Labels: automation, ci, enhancement

#559 fix: opbeans - disabling cgo
  docker/opbeans/go/Dockerfile
Labels: automation, enhancement

#561 fix: used trustworthy Docker images
  .ci/scripts/gren
  .ci/scripts/shellcheck
  .ci/scripts/yamllint
Labels: automation, ci

#566 ci: update JJBB to ignore branches which are also filled as PRs
  .ci/jobs/apm-integration-tests.yml
Labels: automation, ci

#564 ci: enable junit reporting for the pre-commit stage
  .ci/Jenkinsfile
Labels: [zube]: Inbox, automation, ci, enhancement

#556 feat: enable opbeans customisation
  .ci/integrationTestSelector.groovy
  .ci/scripts/opbeans.sh
  README.md
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/run.sh
  docker/opbeans/go/Dockerfile
  docker/opbeans/java/Dockerfile
  docker/opbeans/node/Dockerfile
  docker/opbeans/python/Dockerfile
  docker/opbeans/ruby/Dockerfile
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: [zube]: In Review, automation, enhancement
