Repository elastic/apm-integration-testing, pull requests merged in 2019-05, with the labels that each got.

#426 [APM-CI][Integration Tests] Add as explicit value in the IT choice param
  .ci/integrationTestDownstream.groovy
  JenkinsfileAxis
Labels: automation, ci

#430 [APM-CI][Integration Tests][6.x] Add as explicit value in the IT choice param
  JenkinsfileAxis
Labels: automation, bug, ci

#429 [APM-CI][Integration test][RUM][6.x] Fix issues when using npm@latest
  docker/rum/Dockerfile
Labels: automation

#428 [APM-CI][Integration test][RUM] Fix issues when using npm@latest
  docker/rum/Dockerfile
Labels: automation

#437 [APM-CI][All] Make the trigger by comment case-insensitive
  .ci/Jenkinsfile
  Jenkinsfile
Labels: automation

#424 [APM-CI][Integration Tests] Support dotnet agent
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/packer_cache.sh
  .ci/scripts/all.sh
  .ci/scripts/dotnet.sh
  .gitignore
  API.md
  Jenkinsfile
  JenkinsfileAxis
  Makefile
  QUICKSTART.md
  README.md
  conftest.py
  docker/dotnet/Dockerfile
  docker/dotnet/NuGet.Config
  docker/dotnet/aspnetcore/Dockerfile
  docker/dotnet/aspnetcore/Startup.cs
  docker/dotnet/aspnetcore/appsettings.json
  docker/dotnet/run.sh
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/NuGet.Config
  docker/opbeans/dotnet/run.sh
  scripts/compose.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  tests/agent/concurrent_requests.py
  tests/agent/test_dotnet.py
  tests/agent/test_multiple_agents.py
  tests/fixtures/agents.py
  tests/fixtures/default.py
  tests/versions/dotnet.yml
Labels: automation

#431 ci(jenkins): add node Docker images to the packer cache
  .ci/packer_cache.sh
Labels: automation

#445 [APM-CI][Integration Tests][.Net] Fix building issues
  docker/dotnet/Dockerfile
  docker/dotnet/run.sh
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/run.sh
  tests/versions/dotnet.yml
Labels: automation

#448 [APM-CI][Integration Tests] Enable Dot NET choice parameter
  JenkinsfileAxis
Labels: automation, ci

#450 [APM-CI][Integration Tests] Enable Dot NET choice parameter
  JenkinsfileAxis
Labels: automation, backport, ci

#446 [APM-CI] Cache JRuby docker images
  .ci/packer_cache.sh
Labels: automation, ci

#435 [APM-CI][Integration Tests][GO] Move to Go modules to fix versions
  docker/go/nethttp/Dockerfile
  docker/go/nethttp/go.mod
  docker/go/nethttp/go.sum
  docker/opbeans/go/Dockerfile
Labels: automation

#432 ci(jenkins): add support to run Packetbeat to grab network traffic info during integration test
  .ci/integrationTestDownstream.groovy
  Dockerfile
  JenkinsfileAxis
  README.md
  conftest.py
  docker/packetbeat/packetbeat.yml
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: automation

#438 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#456 [APM-CI][Integration test] Artifacts name has changed
  scripts/compose.py
Labels: automation
