Repository elastic/apm-integration-testing, pull requests merged in 2019-12, with the labels that each got.

#678 fix: define ELASTIC_APM_VERIFY_SERVER_CERT only on Python latest versions
  docker/python/django/Dockerfile
  docker/python/flask/Dockerfile
  scripts/modules/apm_agents.py
  tests/versions/python.yml
Labels: automation, bug

#692 fix: remove whitespaces from label
  .ci/integrationTestDownstream.groovy
Labels: automation, bug

#694 ci(jenkins): simplify the git base commit and avoid docker in the labels
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
Labels: automation, ci

#698 Document pytest markers
  pytest.ini
Labels: automation

#703 Sort options and separate by newline
  scripts/modules/cli.py
Labels: automation, enhancement

#695 Add flags combination to the docs
  README.md
Labels: [zube]: In Review, automation

#707 Add reference repo for apm-integration-testing
  .ci/Jenkinsfile
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
  .ci/jobs/apm-integration-tests.yml
Labels: automation, ci
