Repository elastic/apm-integration-testing, pull requests merged in 2019-10, with the labels that each got.

#620 Bump dotnet agent version 1.1.1
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
Labels: automation

#622 [6.x] (rum): run build on all RUM packages
  docker/rum/Dockerfile
  docker/rum/run.sh
Labels: automation, backport, bug

#621 [7.x] (rum): run build on all RUM packages
  docker/rum/Dockerfile
  docker/rum/run.sh
Labels: automation, backport, bug

#625 fix: use agent fixed versions
  .ci/scripts/7.0-upgrade.sh
Labels: automation, bug, ci

#626 bump 1.1.2 dotnet
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
Labels: automation

#628 fix: upgrade test
  .ci/scripts/7.0-upgrade.sh
  docker/go/nethttp/Dockerfile
Labels: automation, bug, ci

#629 Fix upgrade test
  .ci/scripts/7.0-upgrade.sh
  docker/opbeans/go/Dockerfile
Labels: automation, bug, ci

#635 lighter docker image for the obpeans-dotnet
  docker/dotnet/Dockerfile
  docker/opbeans/dotnet/Dockerfile
Labels: automation

#631 lighter docker image for the obpeans-ruby
  docker/opbeans/ruby/Dockerfile
  docker/opbeans/ruby/entrypoint.sh
  scripts/modules/helpers.py
  scripts/modules/opbeans.py
  scripts/tests/localsetup_tests.py
Labels: automation

#640 fix: incorrect Go version on Dockerfile
  docker/go/nethttp/Dockerfile
Labels: automation, bug, ci

#641 Adds a basic agent remote config test.
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  tests/agent/__init__.py
  tests/agent/test_python.py
Labels: test

#647 fix: linting errors
  .ci/scripts/8.0-upgrade.sh
  .ci/scripts/agent.sh
  .ci/scripts/all.sh
  .ci/scripts/dotnet.sh
  .ci/scripts/go.sh
  .ci/scripts/java.sh
  .ci/scripts/kibana.sh
  .ci/scripts/nodejs.sh
  .ci/scripts/opbeans.sh
  .ci/scripts/python.sh
  .ci/scripts/ruby.sh
  .ci/scripts/rum.sh
  .ci/scripts/server.sh
  .ci/scripts/unit-tests.sh
Labels: automation, bug, ci

#649 feat: add more Node.js Docker images to the cache
  .ci/packer_cache.sh
Labels: automation, ci, enhancement

#652 test: add 6.x version to the test
  .ci/Jenkinsfile
  scripts/compose.py
  tests/versions/apm_server.yml
Labels: automation, ci, test

#651 test: add 6.x version to the test
  .ci/Jenkinsfile
  scripts/compose.py
  tests/versions/apm_server.yml
Labels: automation, ci, test

#648 feat: allow to disable loadgen
  scripts/modules/cli.py
  scripts/tests/localsetup_tests.py
Labels: automation, ci, enhancement

#655 feat: enable OSS artifacts on test
  tests/versions/apm_server.yml
Labels: automation, ci, test

#650 test: add 7.x version to the test
  .ci/Jenkinsfile
  .ci/scripts/common.sh
  scripts/compose.py
  tests/versions/apm_server.yml
Labels: automation, ci, test

#658 fix: Docker images to work with latest changes
  docker/opbeans/node/Dockerfile
  docker/opbeans/ruby/Dockerfile
Labels: automation, bug, ci
