Repository elastic/apm-integration-testing, pull requests merged in 2019-03, with the labels that each got.

#352 [APM-CI] put docker-compose in quiet mode
  Jenkinsfile
  JenkinsfileAxis
  scripts/compose.py
Labels: automation

#347 [6.x] remove bootstrap command in rum image (#339)
  docker/rum/Dockerfile
  scripts/tests/localsetup_tests.py
Labels: backport

#361 [APM-CI] fix checkout
  Jenkinsfile
  JenkinsfileAxis
Labels: automation, backport

#362 [APM-CI] fix checkout
  Jenkinsfile
  JenkinsfileAxis
Labels: automation, backport

#364 remove --release from 6.7 AMMP server version
  tests/versions/python.yml
Labels: automation

#367 Fix lint errors
  scripts/compose.py
Labels: automation

#371 backport fix RUM agent
  docker/rum/Dockerfile
  docker/rum/run.sh
  scripts/compose.py
Labels: automation

#375 [6.x] update build status badge for new jenkins (#374)
  README.md
Labels: backport

#376 [6.x-v1] update build status badge for new jenkins (#374)
  README.md
Labels: backport

#383 [APM-CI] not use flyweight Jenkins agents
  Jenkinsfile
  JenkinsfileAxis
Labels: automation

#382 [APM-CI] not use flyweight Jenkins agents
  Jenkinsfile
  JenkinsfileAxis
Labels: automation

#381 [APM-CI] not use flyweight Jenkins agents
  Jenkinsfile
  JenkinsfileAxis
Labels: automation

#379 [APM-CI] ignore errors when get docker info
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
Labels: automation

#378 [APM-CI] ignore errors when get docker info
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
Labels: automation

#377 [APM-CI] ignore errors when get docker info
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
Labels: automation

#385 [APM-CI] store docker info in folders
  Jenkinsfile
  JenkinsfileAxis
  scripts/docker-get-logs.sh
Labels: automation

#384 [APM-CI] store docker info in folders
  Jenkinsfile
  JenkinsfileAxis
  scripts/docker-get-logs.sh
Labels: automation

#380 [APM-CI] store docker info in folders
  Jenkinsfile
  JenkinsfileAxis
  scripts/docker-get-logs.sh
Labels: automation

#391 fix(rum): build e2e bundles before running tests
  docker/rum/Dockerfile
Labels: automation

#392 fix(rum): build e2e bundles before running tests
  docker/rum/Dockerfile
Labels: automation

#386 [APM-CI] stabilize integration test
  .editorconfig
  Jenkinsfile
  JenkinsfileAxis
  Makefile
  conftest.py
  docker/rum/Dockerfile
  scripts/ci/all.sh
  scripts/ci/common.sh
  scripts/ci/rum.sh
  scripts/compose.py
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  tests/agent/concurrent_requests.py
  tests/agent/test_multiple_agents.py
  tests/agent/test_python.py
  tests/versions/rum.yml
Labels: automation

#396 fix change request detection condition
  Jenkinsfile
Labels: automation

#394 [APM-CI] stabilize integration test 6.x-v1
  Jenkinsfile
  JenkinsfileAxis
  Makefile
  docker/rum/Dockerfile
  scripts/ci/all.sh
  scripts/ci/common.sh
  scripts/compose.py
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
  tests/agent/concurrent_requests.py
Labels: automation

#393 [APM-CI] stabilize integration test 6.x
  .editorconfig
  Jenkinsfile
  JenkinsfileAxis
  Makefile
  conftest.py
  docker/rum/Dockerfile
  scripts/ci/all.sh
  scripts/ci/common.sh
  scripts/ci/rum.sh
  scripts/compose.py
  scripts/docker-get-logs.sh
  scripts/docker-summary.sh
  tests/agent/concurrent_requests.py
  tests/agent/test_multiple_agents.py
  tests/agent/test_python.py
  tests/versions/rum.yml
Labels: automation

#404 [APM-CI] enable Python tests
  scripts/ci/all.sh
  tests/agent/test_multiple_agents.py
Labels: automation

#403 [APM-CI] enable Python tests
  Jenkinsfile
  scripts/ci/all.sh
  tests/agent/test_multiple_agents.py
  tests/agent/test_python.py
Labels: automation

#182 opbeans: allow new customers to be insert
  docker/opbeans/sql/opbeans.sql
  docker/opbeans/sql/opbeans.sql.gz
Labels: [zube]: Inbox

#399 [APM-CI] UI stage to check schemas
  Jenkinsfile
  JenkinsfileAxis
  scripts/ci/common.sh
  scripts/ci/ui.sh
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/clone-kibana.sh
Labels: automation

#406 Python don't find latest version
  docker/opbeans/python/entrypoint.sh
  scripts/ci/python.sh
  scripts/ci/versions_nodejs.sh
  scripts/ci/versions_python.sh
  scripts/ci/versions_ruby.sh
Labels: automation

#407 Python don't find latest version 6.x
  docker/opbeans/python/entrypoint.sh
  scripts/ci/python.sh
  scripts/ci/versions_nodejs.sh
  scripts/ci/versions_python.sh
  scripts/ci/versions_ruby.sh
  tests/versions/python.yml
Labels: automation
