Repository elastic/apm-integration-testing, pull requests merged in 2020-06, with the labels that each got.

#848 ci: use dockerLogs step
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
  scripts/docker-get-logs.sh
Labels: automation, ci

#856 [7.x] Fetch .NET Agent version from VersionPrefix (#849)
  docker/dotnet/run.sh
  docker/opbeans/dotnet/run.sh
Labels: backport

#854 [7.x] ci(docs): generate debug docs with the data (#814)
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
Labels: backport

#855 [7.x] ci(jenkins): enable opbeans validation in apm agents PRs (#763)
  .ci/integrationTestSelector.groovy
  .ci/scripts/opbeans-app.sh
  .ci/scripts/opbeans-rum.sh
  README.md
  docker/opbeans/go/Dockerfile
  docker/opbeans/ruby/entrypoint.sh
Labels: backport

#857 [7.x] feat: enable opbeans customisation (#556)
  .ci/integrationTestSelector.groovy
  .ci/scripts/opbeans.sh
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/java/Dockerfile
  docker/opbeans/node/Dockerfile
  docker/opbeans/python/Dockerfile
  docker/opbeans/ruby/Dockerfile
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: backport

#858 [7.x] ci: aggregate downstream test results (#835)
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: backport

#859 [7.x] ci: use dockerLogs step (#848)
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
  scripts/docker-get-logs.sh
Labels: backport

#860 fix docker images for the opbeans
  scripts/compose.py
  scripts/tests/localsetup_tests.py
Labels: automation

#861 Update eck versions
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, ci

#862 fix: check that docker is installed
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, bug, ci
