Repository elastic/apm-integration-testing, pull requests merged in 2020-12, with the labels that each got.

#1001 Bump docker pip dependencies that are broken
  requirements.txt
Labels: automation, bug

#999 Bump APM Server to 7.10 release
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/7.0-upgrade.sh
  .ci/scripts/common.sh
Labels: automation, enhancement

#1002 Download maven dependencies firstly
  docker/java/spring/maven-package.sh
  docker/opbeans/java/build-agent.sh
Labels: automation

#1014 chore: bump Elastic stack
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: automation, ci, team:automation
