Repository elastic/apm-integration-testing, pull requests merged in 2020-11, with the labels that each got.

#954 ci: store docker logs only if it fails
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
Labels: [zube]: In Review, automation, ci, enhancement, team:automation

#956 [7.x] ci: store docker logs only if it fails (#954)
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: [zube]: In Review, automation, backport, team:automation

#958 fix: update PyYAML to work with Python 3.9.0
  requirements.txt
Labels: automation, bug, ci, team:automation

#957 fix: the variable label does not exist
  .ci/integrationTestSelector.groovy
Labels: automation, bug, ci, team:automation

#959 fix: disable the Elasticsearch dump by default
  .dockerignore
  conftest.py
Labels: automation, bug, team:automation

#960 fix: pip broken dependencies
  requirements.txt
Labels: automation, bug, team:automation

#961 fix: execute remove_env.sh only if docker-info is generated
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, bug, ci, team:automation

#967 fix: change yaml.load to yaml.safe_load
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: automation, chore, team:automation

#968 feta: add a wait container
  Makefile
  requirements.txt
  scripts/modules/aux_services.py
  scripts/modules/cli.py
  scripts/tests/localsetup_tests.py
Labels: automation, enhancement, team:automation

#973 fix: ignore load generator on th wait container
  scripts/modules/aux_services.py
Labels: automation, bug, team:automation

#974 fix: remove relative import from compose.py
  scripts/compose.py
Labels: automation, bug, team:automation

#965 fix: skip chrome and firefox downloads on the RUM agent Docker image
  Makefile
  docker/rum/Dockerfile
Labels: automation, bug, team:automation

#978 [php] use latest release
  docker/php/apache/run.sh
  tests/versions/php.yml
Labels: automation, ci

#982 Fix 7.4.2 to 7.4
  scripts/modules/cli.py
Labels: bug

#976 [7.x] fix: skip chrome and firefox downloads on the RUM agent Docker image (#965)
  Makefile
  docker/rum/Dockerfile
Labels: automation, backport, ci, team:automation

#977 [6.x] fix: skip chrome and firefox downloads on the RUM agent Docker image (#965)
  Makefile
  docker/rum/Dockerfile
Labels: automation, backport, ci, team:automation

#975 fix: retry maven download
  docker/java/spring/maven-package.sh
Labels: automation, ci, team:automation

#991 Support http.enabled in beats
  README.md
  docker/filebeat/filebeat.yml
  docker/heartbeat/heartbeat.yml
  docker/metricbeat/metricbeat.yml
  docker/packetbeat/packetbeat.yml
  scripts/modules/beats.py
  scripts/tests/service_tests.py
Labels: automation, enhancement

#993 Fix packetbeat kibana user/pass
  docker/packetbeat/packetbeat.6.x-compat.yml
  docker/packetbeat/packetbeat.yml
  scripts/modules/beats.py
  scripts/tests/service_tests.py
Labels: automation, bug

#994 chore: bump Elastic Stack
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, chore, team:automation

#983 Use cached .m2 dependencies
  .ci/scripts/agent.sh
  .ci/scripts/all.sh
  .ci/scripts/java.sh
  .gitignore
  docker/java/spring/.m2/.gitkeep
  docker/java/spring/Dockerfile
  docker/java/spring/maven-package.sh
  scripts/modules/apm_agents.py
  scripts/tests/service_tests.py
Labels: automation, enhancement

#996 [lint] fix linting
  .gitignore
Labels: automation, chore
