Repository elastic/apm-integration-testing, pull requests merged in 2020-05, with the labels that each got.

#825 Bump APM Server to 7.7 release
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/scripts/7.0-upgrade.sh
  scripts/compose.py
  tests/versions/apm_server.yml
Labels: [zube]: In Review, automation

#836 fix: debug for apm-server
  scripts/modules/elastic_stack.py
  scripts/tests/service_tests.py
Labels: automation, bug

#835 ci: aggregate downstream test results
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: automation, ci

#840 Update Jaeger instructions for sampling
  README.md
Labels: docs

#841 feat: update Elastic Stack versions to test
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, enhancement

#842 fix: fix typo
  .ci/integrationTestEC.groovy
Labels: automation, bug

#847 fix: apm-server running issues
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: automation
