Repository elastic/apm-integration-testing, pull requests merged in 2020-04, with the labels that each got.

#811 packer: fetch docker images in the apm-server
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation

#812 ci(jjbb): less consume of GH api quota
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
  .ci/jobs/apm-integration-tests.yml
  .ci/jobs/defaults.yml
Labels: automation

#814 ci(docs): generate debug docs with the data
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
Labels: automation, bug, ci

#815 fix: RUM health check
  docker/opbeans/rum/Dockerfile
  docker/opbeans/rum/tasks.js
  docker/rum/Dockerfile
Labels: automation, bug

#819 Enable APIKey in the agents
  README.md
  scripts/create-api-key.sh
  scripts/modules/apm_agents.py
  scripts/modules/elastic_stack.py
  scripts/modules/service.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation, enhancement

#820 Enable TLS for Kibana and Elasticsearch
  scripts/modules/elastic_stack.py
  scripts/modules/helpers.py
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  scripts/tls/apm-server/cert.crt
  scripts/tls/apm-server/key.pem
  scripts/tls/ca/ca.crt
  scripts/tls/elasticsearch/elasticsearch.crt
  scripts/tls/elasticsearch/elasticsearch.key
  scripts/tls/kibana/kibana.crt
  scripts/tls/kibana/kibana.key
Labels: [zube]: In Review, automation, enhancement

#827 [7.x] docker/apm-server: don't copy fields.yml (#823) (41631e8e)
  docker/apm-server/Dockerfile
Labels: automation, backport

#828 fix: update stack version
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: [zube]: In Review, automation, ci

#831 fix: disable telemetry on 7.5+
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: [zube]: In Review, automation, enhancement

#834 support apm-server debug
  scripts/modules/elastic_stack.py
  scripts/tests/service_tests.py
Labels: automation
