Repository elastic/apm-integration-testing, pull requests merged in 2020-01, with the labels that each got.

#710 ci(jenkins): env variables for pre-commit are not required
  .ci/Jenkinsfile
  .ci/integrationTestSelector.groovy
Labels: automation, ci

#705 ci(jenkins): cache php alpine docker images
  .ci/packer_cache.sh
Labels: automation, ci

#709 Introdce APM_SERVICE_VERSION
  .gitignore
  scripts/modules/helpers.py
  scripts/modules/opbeans.py
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
Labels: automation, ci

#713 fix: set branch for UI test
  .ci/scripts/ui.sh
Labels: automation, bug, ci

#716 [7.x] fix: set branch for UI test (#713)
  .ci/scripts/ui.sh
Labels: automation, backport, ci

#693 ci(jenkins): walkthrough document to help with the debugging locally
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
  .gitignore
Labels: automation, enhancement

#702 ci(jenkins): Customise login with an assistance message
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: automation, enhancement

#717 fix: set MERGE_TARGET as branch instead of INTEGRATION_TESTING_VERSION
  .ci/scripts/ui.sh
Labels: automation, bug, ci

#719 [7.x] fix: set MERGE_TARGET as branch instead of INTEGRATION_TESTING_VERSION (#717)
  .ci/scripts/ui.sh
Labels: automation, backport, ci

#718 ci(jenkins): report downstream issues
  .ci/Jenkinsfile
Labels: automation, ci

#725 fix: bump Go version to build the APM Server Docker image
  docker/apm-server/Dockerfile
Labels: automation, ci

#736 chore: refactor scripts
  .ci/scripts/8.0-upgrade.sh
  .ci/scripts/agent.sh
  .ci/scripts/dotnet.sh
  .ci/scripts/go.sh
  .ci/scripts/java.sh
  .ci/scripts/kibana.sh
  .ci/scripts/nodejs.sh
  .ci/scripts/opbeans.sh
  .ci/scripts/python.sh
  .ci/scripts/ruby.sh
  .ci/scripts/rum.sh
  .ci/scripts/server.sh
  .ci/scripts/unit-tests.sh
Labels: automation, enhancement

#734 Refresh interval
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: automation, enhancement

#731 feat: document how to bump Elastic Stack version
  README.md
Labels: automation, docs

#730 feat: bump Elastic Stack version to 7.6
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/7.0-upgrade.sh
  scripts/compose.py
  tests/versions/apm_server.yml
Labels: automation, ci

#739 Minor grammar fixes
  README.md
Labels: automation, docs

#740 fix: update Elastic Stack versions
  scripts/modules/cli.py
Labels: automation, chore

#733 feat: moving to Python 3
  Makefile
  README.md
Labels: automation, ci

#728 feat: moving to Python 3
  Makefile
  README.md
Labels: automation, ci

#746 test: enclose versions between quotes
  tests/versions/apm_server.yml
Labels: automation, bug, ci

#735 feat: YAML output.
  scripts/modules/cli.py
Labels: [zube]: In Review, automation, enhancement

#738 feat: flag to set the Kibana URL for the APM Server
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation, enhancement

#750 fix: no set xpack.apm.serviceMapEnabled on Kibana OSS
  scripts/modules/elastic_stack.py
Labels: automation, bug, ci
