Repository elastic/apm-integration-testing, pull requests merged in 2020-07, with the labels that each got.

#866 feat: configure retries on tests
  Makefile
  conftest.py
  pytest.ini
  requirements.txt
Labels: automation, enhancement, team:automation

#869 [6.x-v1] feat: bump pytest version (#866)
  Makefile
  pytest.ini
  requirements.txt
Labels: automation, team:automation

#867 [7.x] feat: bump pytest version (#866)
  Makefile
  conftest.py
  pytest.ini
  requirements.txt
Labels: automation, team:automation

#868 [6.x] feat: bump pytest version (#866)
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  Makefile
  conftest.py
  pytest.ini
  requirements.txt
Labels: automation, team:automation

#875 [6.x-v1] fix: update dependencies to run integration tests (#872)
  docker/rum/Dockerfile
Labels: automation, bug, team:automation

#874 [6.x] fix: update dependencies to run integration tests (#872)
  docker/rum/Dockerfile
Labels: automation, bug, team:automation

#873 [7.x] fix: update dependencies to run integration tests (#872)
  docker/rum/Dockerfile
Labels: automation, bug, team:automation

#878 fix: remove chrome drive is not used
  Dockerfile
Labels: automation, bug, team:automation

#876 fix: remove chrome drive is not used
  Dockerfile
Labels: automation, bug, team:automation

#877 fix: remove chrome drive is not used
  Dockerfile
Labels: automation, bug, team:automation

#880 fix: add libxss dependency to the opbean-rum
  docker/opbeans/rum/Dockerfile
Labels: automation, bug, team:automation

#883 [6.x-v1] fix: add libxss dependency to the opbean-rum (#880)
  docker/opbeans/rum/Dockerfile
Labels: automation, bug, team:automation

#882 [6.x] fix: add libxss dependency to the opbean-rum (#880)
  docker/opbeans/rum/Dockerfile
Labels: automation, bug, team:automation

#881 [7.x] fix: add libxss dependency to the opbean-rum (#880)
  docker/opbeans/rum/Dockerfile
Labels: automation, bug, team:automation

#885 ci: use downstream job accordingly
  .ci/Jenkinsfile
Labels: automation

#886 fix: update Elastic Stack versions
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: [zube]: In Review, automation, chore, team:automation

#888 fix: update Elastic Stack versions
  .ci/integrationTestECK.groovy
Labels: automation, bug, team:automation

#892 chore: update Elastic Stack version
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: automation, chore, team:automation

#890 feat: allow to pass extra options to the RUM agent
  docker/opbeans/frontend_nginx/entrypoint.sh
  docker/opbeans/frontend_nginx/rum-config.template
Labels: [zube]: In Review, automation, enhancement, team:automation

#891 fix: update Go version to the latest LTS version
  docker/go/nethttp/Dockerfile
Labels: automation, bug, ci, team:automation

#893 fix: retry npm install
  docker/opbeans/rum/Dockerfile
  docker/rum/Dockerfile
Labels: automation, bug, team:automation
