Repository elastic/apm-integration-testing, pull requests merged in 2020-03, with the labels that each got.

#700 Run integration tests on Elastic Cloud
  .ci/integrationTestEC.groovy
  .ci/jobs/apm-it-ec.yml
  Makefile
  conftest.py
  requirements.txt
  tests/fixtures/default.py
  tests/fixtures/es.py
  tests/utils.py
Labels: [zube]: In Review, automation, ci, enhancement

#701 Run integration tests on ECK
  .ci/integrationTestECK.groovy
  .ci/jobs/apm-it-eck.yml
Labels: [zube]: In Review, automation, ci, enhancement

#786 Add Kibana encryptionKey
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: [zube]: Inbox

#788 Add Elasticsearch slowlog flag
  scripts/modules/elastic_stack.py
  scripts/modules/helpers.py
Labels: automation, enhancement

#790 fix: method too long error
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/all.sh
  .ci/scripts/remove_env.sh
  Dockerfile
  Makefile
  scripts/modules/cli.py
  tests/fixtures/default.py
  tests/fixtures/es.py
  tests/utils.py
Labels: [zube]: In Review, automation, bug, ci

#791 fix: launch jobs only on cron trigger
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
Labels: automation, ci, enhancement

#793 dotnet: sdk version and fail-fast
  docker/dotnet/Dockerfile
  docker/dotnet/run.sh
Labels: automation

#794 opbeans-dotnet: bump sdk version and fail fast
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/run.sh
Labels: automation

#792 ci: remove 8 Stack version temporarily on ECK test
  .ci/integrationTestECK.groovy
Labels: [zube]: In Review, automation, ci

#795 refactor: reuse remove-project from apm-agent-dotnet
  docker/dotnet/run.sh
  docker/opbeans/dotnet/run.sh
Labels: [zube]: In Review, automation

#796 [7.x] dotnet: bump sdk version and fail-fast (#793)
  docker/dotnet/Dockerfile
  docker/dotnet/run.sh
Labels: backport

#797 [7.x] opbeans-dotnet: bump sdk version and fail fast (#794)
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/run.sh
Labels: backport

#799 [7.x] Update TestAspNetCoreApp.csproj (#754)
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
Labels: [zube]: In Review, automation, backport

#798 [7.x] refactor: reuse remove-project from apm-agent-dotnet (#795)
  docker/dotnet/run.sh
  docker/opbeans/dotnet/run.sh
Labels: backport

#802 fix: openjdk:10-jre-slim no longer can install packages
  .ci/packer_cache.sh
  docker/java/spring/Dockerfile
Labels: automation, bug, ci

#803 feat: return the exit code of docker compose in case of failure
  scripts/modules/cli.py
Labels: automation, enhancement

#806 fix: apm-server docker container test
  docker/apm-server/Dockerfile
Labels: automation, bug

#808 fix: bump snapshot version
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: [zube]: In Review, automation, ci
