Repository elastic/apm-integration-testing, pull requests merged in 2020-10, with the labels that each got.

#940 chore: bump stack versions
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: automation, chore, team:automation

#941 chore: bump stack versions
  tests/versions/apm_server.yml
Labels: automation, chore

#943 add --kibana-yml option
  docker/kibana/kibana.yml
  scripts/modules/elastic_stack.py
  scripts/tests/service_tests.py
Labels: enhancement

#944 fix: change to use adoptOpenJDK to fix the build
  docker/java/spring/Dockerfile
Labels: automation, bug, team:automation

#945 [6.x] fix: change to use adoptOpenJDK to fix the build (#944)
  docker/java/spring/Dockerfile
Labels: backport

#946 Support PHP ITs
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/php.sh
  README.md
  docker/php/apache/Dockerfile
  docker/php/apache/run.sh
  scripts/modules/apm_agents.py
  scripts/tests/service_tests.py
  tests/versions/php.yml
Labels: automation, ci

#950 fix: remove APM Server kibana setting when you set --no-kibana
  scripts/modules/elastic_stack.py
Labels: automation, bug, team:automation

#949 [CI] selector and downstream use different commands
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/generate-debug-docs.sh
Labels: automation, ci, docs

#952 chore: update stack versions
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: [zube]: In Review, automation, chore, team:automation

#953 [CI] Aggregate all the tests from all the stages
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
Labels: automation, bug, ci
