Repository elastic/apm-integration-testing, pull requests merged in 2020-02, with the labels that each got.

#751 fixes: use superuser rather than the kibana_system_user
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: automation

#757 fix: change the way we configure the RUM agent
  docker/opbeans/frontend_nginx/default.template
  docker/opbeans/frontend_nginx/entrypoint.sh
  docker/opbeans/frontend_nginx/rum-config.template
Labels: automation, ci

#759 opbeans-dotnet: support dotnet agent version >= 1.3 and < 1.3
  docker/opbeans/dotnet/run.sh
Labels: automation, bug

#760 dotnet: support dotnet agent version >= 1.3 and < 1.3
  docker/dotnet/run.sh
Labels: automation, bug

#737 feat: test APM Server with TLS and a Token configured
  .ci/scripts/all.sh
  Makefile
  tests/fixtures/default.py
  tests/utils.py
Labels: [zube]: In Review, automation, enhancement

#761 [7.x] opbeans-dotnet: support dotnet agent version >= 1.3 and < 1.3 (#759)
  docker/opbeans/dotnet/run.sh
Labels: backport

#762 [7.x] dotnet: support dotnet agent version >= 1.3 and < 1.3 (#760)
  docker/dotnet/run.sh
Labels: backport

#764 Remove Kibana test
  Dockerfile
  tests/kibana/test_integration.py
Labels: chore, test

#767 [7.x] Upgrade APM Server to python 3 (#766)
  docker/apm-server/Dockerfile
Labels: backport

#769 apm-ui: use the new kibana project layout
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/clone-kibana.sh
Labels: automation

#771 [apm-ui] File names don't match the previous expected ones
  .pre-commit-config.yaml
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/download-sample-docs.ts
Labels: automation

#776 [7.x] apm-ui: use the new kibana project layout (#769)
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/clone-kibana.sh
Labels: backport

#777 [7.x] [apm-ui] File names don't match the previous expected ones (#771)
  .pre-commit-config.yaml
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/download-sample-docs.ts
Labels: backport

#779 ci(jenkins): Agent when required
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: [zube]: In Progress, automation, ci

#763 ci(jenkins): enable opbeans
  .ci/integrationTestSelector.groovy
  .ci/scripts/opbeans-app.sh
  .ci/scripts/opbeans-rum.sh
  README.md
  docker/opbeans/dotnet/run.sh
  docker/opbeans/go/Dockerfile
  docker/opbeans/ruby/entrypoint.sh
Labels: [zube]: In Review, automation, ci, enhancement
