Repository elastic/apm-integration-testing, pull requests merged in 2020-09, with the labels that each got.

#903 [6.x] fix: missing dependencies for rum test (#899)
  docker/opbeans/rum/Dockerfile
  docker/rum/Dockerfile
Labels: backport

#902 [7.x] fix: missing dependencies for rum test (#899)
  docker/opbeans/rum/Dockerfile
  docker/rum/Dockerfile
Labels: backport

#907 fix: use fixed version of setuptools
  requirements.txt
Labels: automation, bug, ci, team:automation

#908 [7.x] fix: use fixed version of setuptools (#907)
  requirements.txt
Labels: backport

#909 [6.x] fix: use fixed version of setuptools (#907)
  requirements.txt
Labels: backport

#904 fix: update JDK and apply some maven options
  docker/java/spring/Dockerfile
  docker/java/spring/maven-package.sh
  docker/opbeans/java/Dockerfile
  docker/opbeans/java/build-agent.sh
Labels: automation, bug, ci, team:automation

#911 [6.x] fix: update JDK and apply some maven options (#904)
  docker/java/spring/Dockerfile
  docker/java/spring/maven-package.sh
  docker/opbeans/java/Dockerfile
Labels: backport

#910 [7.x] fix: update JDK and apply some maven options (#904)
  docker/java/spring/Dockerfile
  docker/java/spring/maven-package.sh
  docker/opbeans/java/Dockerfile
  docker/opbeans/java/build-agent.sh
Labels: backport

#912 [CI] fixes No artifacts found
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
Labels: automation, bug, ci

#915 fix: RUM Docker image build
  docker/rum/Dockerfile
Labels: automation, bug, ci, team:automation

#916 [7.x] fix: RUM Docker image build (#915)
  docker/rum/Dockerfile
Labels: backport

#917 chore: no execute `npm audit`
  docker/rum/Dockerfile
Labels: automation, chore, ci, team:automation

#918 fix: filter 6.x-v1 tag and other branches
  .ci/jobs/apm-integration-tests.yml
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
Labels: automation, chore, ci, team:automation

#919 chore: Bump Elastic Stack versions
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: automation, chore, ci, team:automation

#914 [7.x] [CI] fixes No artifacts found (#912)
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: automation, backport, ci, team:automation

#921 fix: use Node.js LTS version for ITs
  docker/nodejs/express/Dockerfile
Labels: [zube]: In Review, automation, chore, team:automation

#922 fix: use a Opbeans-go fixed version
  .ci/scripts/7.0-upgrade.sh
Labels: [zube]: In Review, automation, bug, team:automation

#924 [6.x] fix: use Node.js LTS version for ITs (#921)
  docker/nodejs/express/Dockerfile
Labels: backport

#923 [7.x] fix: use Node.js LTS version for ITs (#921)
  docker/nodejs/express/Dockerfile
Labels: backport

#926 chore: update docker images
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, chore, ci, team:automation

#927 fix: increase the resilience against network issues
  docker/java/spring/maven-package.sh
  docker/opbeans/java/build-agent.sh
  docker/opbeans/java/entrypoint.sh
Labels: automation, bug, ci, team:automation

#930 fix: add the parameter repoUrl it is needed by maven-dependency-plugin
  docker/java/spring/maven-package.sh
Labels: automation, bug, ci, regression, team:automation

#929 [6.x] fix: increase the resilience against network issues (#927)
  docker/java/spring/maven-package.sh
  docker/opbeans/java/build-agent.sh
  docker/opbeans/java/entrypoint.sh
Labels: backport

#928 [7.x] fix: increase the resilience against network issues (#927)
  docker/java/spring/maven-package.sh
  docker/opbeans/java/build-agent.sh
  docker/opbeans/java/entrypoint.sh
Labels: backport

#931 Support ubi8 docker images
  scripts/modules/aux_services.py
  scripts/modules/beats.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  tests/versions/apm_server.yml
Labels: automation, enhancement

#934 fix: use Elasticsearch https when is enabled
  scripts/modules/elastic_stack.py
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation, bug, team:automation

#933 fix: bump go version
  docker/apm-server/Dockerfile
Labels: [zube]: In Review, automation, bug, team:automation

#935 [7.x] fix: bump go version (#933)
  docker/apm-server/Dockerfile
Labels: backport
