Repository elastic/apm-integration-testing, pull requests merged in 2021-07, with the labels that each got.

#1200 [automation] Update go release version 1.16.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1198 [automation] Update Elastic stack release version [6.8.17, 7.13.2, 7.13.3, 7.14.0]
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1199 [automation] Update Elastic stack release version [6.8.17, 7.13.2, 7.13.3, 7.14.0]
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1201 Add traces for the make test-helps
  Makefile
Labels: Team:Automation, area:ci, automation, backport

#1205 [Automation] Update elastic stack release version to 7.13.2
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: dependency

#1210 [automation] Update Elastic stack release version [6.8.17, 7.13.3, 7.13.4, 7.14.0]
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1214 fix: wait a little more for Kibana
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: Team:Automation, backport, bug

#1213 fix: Custom headers
  Makefile
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: Team:Automation, backport, bug

#1217 [automation] Update Elastic stack release version [6.8.17, 7.13.3, 7.13.4, 7.14.0]
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1221 [automation] Update go release version 1.16.6
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1220 fix: remove EOL versions
  tests/versions/apm_server.yml
Labels: Team:Automation, chore

#970 feat: build kibana container from sources
  docker/kibana_src/.dockerignore
  docker/kibana_src/Dockerfile
  docker/kibana_src/kibana_src.yml
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: Team:Automation, [zube]: In Review, automation, enhancement

#1222 feat: use terraform deployment
  .ci/integrationTestEC.groovy
Labels: Team:Automation, enhancement
