Repository elastic/apm-integration-testing, pull requests merged in 2021-04, with the labels that each got.

#1098 fix: set destructive_requires_name to false
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: automation, bug, team:automation

#1099 [7.x] fix: set destructive_requires_name to false (#1098)
  scripts/modules/elastic_stack.py
  scripts/tests/localsetup_tests.py
Labels: automation, backport, team:automation

#1097 fix: update dependencies to fix CVE-2021-28918
  docker/opbeans/rum/package-lock.json
  docker/opbeans/rum/package.json
Labels: automation, bug, team:automation

#1105 fix: correct Makefile syntax to spawn a subshell
  Makefile
Labels: bug

#1058 [6.x] test: use filebeat step to grab Docker logs (#1029)
  .ci/integrationTestDownstream.groovy
  .ci/scripts/common.sh
Labels: backport

#1057 [7.x] test: use filebeat step to grab Docker logs (#1029)
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/common.sh
Labels: backport

#1113 fix: add normalize function
  .ci/integrationTestDownstream.groovy
Labels: bug, ci, team:automation

#1115 fix: grab stack version from the library
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestSelector.groovy
Labels: Team:Automation, enhancement

#1118 Automate bump of release versions
  .ci/bump-stack-release-version.sh
Labels: backport, ci

#1119 [mergify]: assign author and backport when merged
  .mergify.yml
Labels: Team:Automation, automation

#1122 [7.x] fix: --opbeans-node-agent-local-repo=/a/local/dir (#1084)
  docker/opbeans/node/Dockerfile
  docker/opbeans/node/entrypoint.sh
Labels: backport

#1123 [7.x] fix: update flake8 and deps to work with Python 3.8+ (#1085)
  requirements.txt
Labels: backport

#1124 [6.x] fix: update flake8 and deps to work with Python 3.8+ (#1085)
  requirements.txt
Labels: backport

#1125 [7.x] fix: drop ancient and conflicting maxQueueSize setting for node.js agent (#1104)
  docker/nodejs/express/app.js
Labels: backport

#1126 [6.x] fix: drop ancient and conflicting maxQueueSize setting for node.js agent (#1104)
  docker/nodejs/express/app.js
Labels: backport

#1127 [7.x] fix: correct Makefile syntax to spawn a subshell (#1105)
  Makefile
Labels: backport

#1128 [6.x] fix: correct Makefile syntax to spawn a subshell (#1105)
  Makefile
Labels: backport

#1129 [7.x] fix: add git to opbeans-node testing container in case npm install needs it (#1107)
  docker/opbeans/node/Dockerfile
Labels: backport

#1130 [7.x] resolve linting errors (#985)
  scripts/upgrade/compare_reindexed.py
  scripts/upgrade/migrate.py
  scripts/upgrade/pipeline.py
  tests/server/test_upgrade.py
Labels: backport

#1133 [automation] update elastic stack release version [7.12.1, 7.13.0]
  scripts/modules/cli.py
Labels: automation, dependency

#1132 [automation] update elastic stack release version [7.12.1, 7.13.0]
  scripts/modules/cli.py
Labels: automation, dependency

#1134 feat: validate docker images using BATS (backport #489)
  .gitmodules
  README.md
Labels: Team:Automation
