Repository elastic/apm-integration-testing, pull requests merged in 2021-06, with the labels that each got.

#1164 Update jaeger gRPC instructions
  README.md
Labels: docs

#1168 [automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1]
  .ci/scripts/common.sh
  scripts/modules/cli.py
  tests/versions/apm_server.yml
Labels: automation, dependency

#1167 [automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1]
  .ci/scripts/common.sh
Labels: automation, dependency

#1172 [automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1, 7.13.2]
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1173 [automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1, 7.13.2]
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1176 [master][automation] update go release version 1.16.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1177 [7.x][automation] update go release version 1.16.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1179 Automatically bump Elastic stack version in EC/ECK pipelines
  .ci/bump-stack-release-version.sh
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: Team:Automation, automation, dependencies

#1181 [automation] Update Elastic stack release version [6.8.16, 7.13.1, 7.13.2]
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1180 [automation] Update go release version 1.16.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1185 Validate the pre-requirements
  scripts/compose.py
Labels: backport
