Repository elastic/apm-integration-testing, pull requests merged in 2021-01, with the labels that each got.

#1009 [CI] use the .ci/settings.xml for the java build
  docker/java/spring/maven-package.sh
  docker/opbeans/java/build-agent.sh
Labels: automation, team:automation

#1015 feat: add /test and /testAll comment triggers
  .ci/Jenkinsfile
Labels: [zube]: In Review, automation, ci, enhancement, team:automation

#1018 [ruby] Support 2.x ruby version and latest
  .ci/Jenkinsfile
  .ci/scripts/ruby.sh
  .pre-commit-config.yaml
  docker/ruby/rails/Dockerfile
  scripts/modules/apm_agents.py
  scripts/tests/service_tests.py
Labels: automation, bug

#1020 [CI] Restore pre-commit run in the worker
  .ci/Jenkinsfile
  .pre-commit-config.yaml
Labels: automation, ci, team:automation

#1019 [ruby] Support 2.x ruby version and latest and backport #635 #995 #1013
  .ci/scripts/ruby.sh
  .pre-commit-config.yaml
  docker/dotnet/Dockerfile
  docker/dotnet/aspnetcore/Startup.cs
  docker/dotnet/aspnetcore/TestAspNetCoreApp.csproj
  docker/dotnet/run.sh
  docker/opbeans/dotnet/Dockerfile
  docker/opbeans/dotnet/run.sh
  docker/ruby/rails/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
  tests/agent/concurrent_requests.py
Labels: automation, ci

#1023 [7.x] feat: add /test and /testAll comment triggers (#1015)
  .ci/Jenkinsfile
Labels: backport

#1025 [ruby] Support 2.x ruby version and latest #1019
  .ci/scripts/ruby.sh
  docker/ruby/rails/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: automation, team:automation

#1021 chore: bump Stack version
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: automation, chore, team:automation

#1026 chore: reduce the day to keep build
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
  .ci/jobs/defaults.yml
Labels: automation, chore, team:automation

#1024 chore: update tested versions
  scripts/compose.py
  tests/versions/apm_server.yml
  tests/versions/dotnet.yml
  tests/versions/go.yml
  tests/versions/java.yml
  tests/versions/ruby.yml
  tests/versions/rum.yml
Labels: automation, chore, team:automation

#1033 fix: lint check is broken
  docker/apm-server/managed/Dockerfile
  docker/apm-server/managed/go.sum
Labels: automation, bug, ci, team:automation

#1041 enable kibana-port
  scripts/modules/elastic_stack.py
Labels: automation, bug

#1040 OSS distribution change for Kibana and Elasticsearch in 7.11+ and 6.8.14+ versions
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
  tests/versions/apm_server.yml
Labels: automation, enhancement

#1038 chore: update EOL stack versions
  tests/versions/apm_server.yml
Labels: automation, chore, team:automation

#1039 feat: notify GitHb Check on axis
  .ci/integrationTestDownstream.groovy
Labels: automation, enhancement, team:automation

#1022 chore: update tested versions
  tests/versions/java.yml
  tests/versions/python.yml
  tests/versions/ruby.yml
Labels: [zube]: In Review, automation, chore, team:automation
