Repository elastic/apm-integration-testing, pull requests merged in 2021-03, with the labels that each got.

#1079 ci: jjbb remove periodic-folder-trigger
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
  .ci/jobs/defaults.yml
Labels: automation

#1086 fix: force to activate Python virtualenv
  Makefile
Labels: automation, bug, team:automation

#1085 fix: update flake8 and deps to work with Python 3.8+
  requirements.txt
Labels: bug

#1088 chore: bump slastic stack versions
  scripts/modules/cli.py
  tests/versions/apm_server.yml
Labels: automation, chore, team:automation

#1091 CI: skip timer trigger on a PR basis
  .ci/Jenkinsfile
Labels: automation, backport

#1090 fix: elastic-agent ensure 7.12 backwards compatibility, add bugfix fleet server
  docker/apm-server/managed/main.go
  scripts/modules/elastic_stack.py
  scripts/tests/service_tests.py
Labels: backport
