Repository elastic/apm-integration-testing, pull requests merged in 2021-11, with the labels that each got.

#1308 [automation] Update go release version 1.17.2
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1316 [mergify] report open backported PRs once a week
  .mergify.yml
Labels: automation, backport-skip

#1320 [automation] Update Elastic stack release version 7.15.2 7.16.0
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1321 [automation] Update Elastic stack release version 7.15.2 7.16.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1323 fix: change 7.x to 7.16.0
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: bug, ci, Team:Automation

#1325 chore: remove oss tests for master
  tests/versions/apm_server.yml
Labels: chore, Team:Automation, area:ci

#1326 chore: do not download Docker images
  .ci/integrationTestECK.groovy
Labels: chore, Team:Automation, area:ci

#1031 test: run APM Server managed
  .ci/scripts/common.sh
Labels: enhancement, [zube]: In Review, automation, Team:Automation
