Repository elastic/apm-integration-testing, pull requests merged in 2021-02, with the labels that each got.

#1051 [7.x] Bump Go version '1.14.12' (#1046)
  .ci/bump/bump-go.sh
  .gitignore
  docker/apm-server/Dockerfile
Labels: automation, backport, ci, team:automation

#1054 fix: bump go version
  docker/apm-server/Dockerfile
Labels: automation, bug, ci, team:automation

#1052 [7.x] enable kibana-port (#1041)
  scripts/modules/elastic_stack.py
Labels: [zube]: In Review, automation, backport, bug, team:automation

#1056 docs: using Dyno
  README.md
  images/apm-dyno.png
  images/dyno.png
Labels: automation, docs, team:automation

#1029 test: use filebeat step to grab Docker logs
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
  .ci/scripts/common.sh
Labels: [zube]: In Review, automation, team:automation, test

#1053 [7.x] OSS distribution change for Kibana and Elasticsearch in 7.11+ and 6.8.14+ versions (#1040)
  scripts/modules/service.py
  scripts/tests/localsetup_tests.py
  scripts/tests/service_tests.py
Labels: [zube]: In Review, automation, backport, team:automation

#1060 chore: bump Elastic Stack
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  scripts/modules/cli.py
Labels: automation, chore, team:automation

#1066 [7.x] fix: bump go version (#1054)
  docker/apm-server/Dockerfile
Labels: automation, backport

#1067 [7.x] docker/go/nethttp: go build -mod=mod (#1061)
  docker/go/nethttp/Dockerfile
Labels: automation, backport

#1064 [7.x] Create opbeans_user/role with write/read access for the opbeans-python (#1063)
  docker/elasticsearch/roles.yml
  docker/elasticsearch/users
  docker/elasticsearch/users_roles
  scripts/modules/opbeans.py
  scripts/tests/localsetup_tests.py
Labels: automation, backport

#1070 [CI] Increase timeout
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
Labels: automation, ci

#1071 [7.x] [CI] Increase timeout (#1070)
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
Labels: automation, backport

#1072 [6.x] [CI] Increase timeout (#1070)
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
Labels: automation, backport
