Repository elastic/apm-integration-testing, pull requests merged in 2021-12, with the labels that each got.

#1331 feat: enable pytest_otel plugin
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/integrationTestSelector.groovy
  Makefile
  requirements.txt
Labels: enhancement, Team:Automation, area:ci

#1336 fix: update the pytest-otel version to the minimum that support auth
  requirements.txt
Labels: bug, Team:Automation

#1342 fix: set the correct APM Server environment variable for the RUM agent
  scripts/modules/apm_agents.py
Labels: bug, Team:Automation

#1343 Update main branch
  .ci/Jenkinsfile
  .ci/integrationTestDownstream.groovy
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/jobs/apm-integration-tests.yml
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
  .mergify.yml
  QUICKSTART.md
  README.md
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/clone-kibana.sh
Labels: automation, Team:Automation

#1350 [automation] Update Elastic stack release version 7.16.1 7.17.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1349 [automation] Update Elastic stack release version 7.16.1 7.17.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1345 mergify: keep the house clean and notify smarter
  .mergify.yml
Labels: backport-skip

#1346 jjbb: keep the mbp tidy
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
Labels: backport-skip

#1357 [automation] Update Elastic stack release version 7.16.2 7.17.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1358 [automation] Update Elastic stack release version 7.16.2 7.17.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency
