Repository elastic/apm-integration-testing, pull requests merged in 2021-09, with the labels that each got.

#1248 [automation] Update Elastic stack release version [7.14.1, 7.15.0]
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1251 [automation] Update Elastic stack release version [7.14.1, 7.15.0]
  .ci/scripts/common.sh
  scripts/modules/cli.py
  tests/versions/apm_server.yml
Labels: automation, dependency

#1252 Add backport label for automating the backport
  .mergify.yml
Labels: area:ci

#1258 [automation] Update go release version 1.17.1
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1274 fix: use toJSON instead of readJSON
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: enhancement
