Repository elastic/apm-integration-testing, pull requests merged in 2022-11, with the labels that each got.

#1531 ci: remove unused variable
  .ci/Jenkinsfile
Labels: automation, Team:Automation

#1530 ci: remove downstream and update pipeline
  .ci/Jenkinsfile
Labels: automation

#1529 [automation] Update Elastic stack release version 7.17.7 7.17.8
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1533 action: use GitHub actions
  .ci/Jenkinsfile
  .ci/jobs/apm-integration-tests.yml
  .ci/jobs/defaults.yml
  .ci/scripts/common.sh
  .github/workflows/ci.yml
  .github/workflows/test-reporter.yml
  .pre-commit-config.yaml
  README.md
Labels: ci, automation, backport

#1536 fix precommit linting
  .ci/scripts/build-docker-all.sh
  .ci/scripts/lint.sh
  .ci/scripts/unit-tests.sh
  docker/apm-server/haproxy/docker-entrypoint.sh
  docker/dyno/app/range.yml
  docker/dyno/package.json
  docker/dyno/tests/__init__.py
  docker/dyno/tests/unit/__init__.py
  docker/dyno/tests/unit/index.test.js
  docker/filebeat/filebeat.yml
  docker/kibana/kibana-8.yml
  docker/kibana/kibana.yml
  docker/opbeans/sql/opbeans.sql
  docker/packetbeat/packetbeat.6.x-compat.yml
  docker/packetbeat/packetbeat.yml
  docker/tests/tests.bats
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/README.md
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/setup.sh
  scripts/tests/config/test_apm_managed.yml
  scripts/tests/config/test_apm_managed_build.yml
Labels: backport

#1538 [automation] Update go release version 1.18.8
  docker/apm-server/Dockerfile
Labels: automation, dependency
