Repository elastic/apm-integration-testing, pull requests merged in 2022-05, with the labels that each got.

#1476 [automation] Update Elastic stack release version 8.2.0 8.2.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1477 ci: add debug traces for the docker containers
  .ci/integrationTestSelector.groovy
  scripts/docker-summary.sh
Labels: backport

#1478 opbeans-dotnet: use core/aspnet:3.1.7-alpine docker image
  docker/opbeans/dotnet/Dockerfile
Labels: backport

#1488 fix: update to pytest-otel 1.1.1
  requirements.txt
Labels: bug, Team:Automation
