Repository elastic/apm-integration-testing, pull requests merged in 2022-03, with the labels that each got.

#1447 [automation] Update Elastic stack release version 7.17.1 7.17.2
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1450 [automation] Update Elastic stack release version 8.1.0 8.2.0
  .ci/scripts/common.sh
Labels: automation, dependency, backport-skip

#1457 fix: Fix auth
  .ci/Jenkinsfile
  .pre-commit-config.yaml
Labels: bug, Team:Automation

#1435 feat: APM server managed on 8+
  Makefile
  docker/elastic-agent/Dockerfile
  docker/elasticsearch/service_tokens
  docker/kibana/kibana-8.yml
  scripts/modules/aux_services.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/modules/service.py
  scripts/tests/config/test_apm_managed.yml
  scripts/tests/config/test_apm_managed_build.yml
  scripts/tests/config/test_start_main_default.yml
  scripts/tests/test_localsetup.py
  scripts/tests/test_service.py
Labels: enhancement, Team:Automation

#1459 feat: APM server managed on 8+ II
  Makefile
  docker/elastic-agent/Dockerfile
  docker/elasticsearch/service_tokens
  docker/kibana/kibana-8.yml
  scripts/modules/aux_services.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/modules/service.py
  scripts/tests/config/test_apm_managed.yml
  scripts/tests/config/test_apm_managed_build.yml
  scripts/tests/config/test_start_main_default.yml
  scripts/tests/test_localsetup.py
  scripts/tests/test_service.py
Labels: enhancement

#1460 fix: use stack version from the APM library
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: bug, Team:Automation

#1462 fix: use versions from the artifactory
  .ci/integrationTestEC.groovy
  .ci/integrationTestECK.groovy
Labels: enhancement, Team:Automation, area:ci
