Repository elastic/apm-integration-testing, pull requests merged in 2022-02, with the labels that each got.

#1407 main: update references for main
  .ci/Jenkinsfile
  QUICKSTART.md
  README.md
  scripts/modules/apm_agents.py
Labels: automation

#1397 apm-server: main
  .ci/bump-go-release-version.sh
  .ci/bump-stack-release-version.sh
  README.md
  docker/apm-server/Dockerfile
  scripts/kibana/validate-ts-interfaces-against-apm-server-sample-docs/scripts/download-sample-docs.ts
  scripts/modules/apm_agents.py
  scripts/modules/cli.py
  scripts/modules/elastic_stack.py
  scripts/tests/test_localsetup.py
  scripts/tests/test_service.py
  tests/versions/apm_server.yml
Labels: automation

#1426 [automation] Update Elastic stack release version 7.17.0 7.17.1
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1432 chore: EOL of 6.x
  .ci/jobs/apm-integration-test-downstream.yml
  .ci/jobs/apm-integration-tests-selector-mbp.yml
  .ci/jobs/apm-integration-tests-upgrade-mbp.yml
  .ci/jobs/apm-integration-tests.yml
  .ci/jobs/apm-it-ec.yml
  .ci/jobs/apm-it-eck.yml
Labels: chore

#1433 fix: Go agent tests
  scripts/modules/apm_agents.py
  scripts/tests/test_service.py
Labels: bug, ci

#1438 [automation] Update Elastic stack release version 7.17.0 7.17.1
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency
