Repository elastic/apm-integration-testing, pull requests merged in 2022-01, with the labels that each got.

#1361 apm-agent-ruby: healthcheck for 3.1 version is broken
  docker/ruby/rails/Dockerfile
  scripts/modules/apm_agents.py
  scripts/tests/test_service.py
Labels: backport, dependencies

#1360 [automation] Update go release version 1.17.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1364 [6.x] apm-agent-ruby: healthcheck for 3.1 version is broken (#1361)
  docker/ruby/rails/Dockerfile
  scripts/compose.py
  scripts/tests/service_tests.py
Labels: backport

#1363 bump automation: use 7.17 branch
  .ci/bump-go-release-version.sh
Labels: automation

#1370 [automation] Update go release version 1.17.5
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1372 [automation] Update Elastic stack release version 7.16.3 7.17.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1377 apm: Neutral naming for apm-agent-php
  README.md
  docker/php/apache/Dockerfile
  scripts/modules/apm_agents.py
  scripts/tests/test_service.py
  tests/versions/php.yml
Labels: automation

#1381 Neutral naming for apm-agent-nodejs
  README.md
  tests/versions/nodejs.yml
Labels: automation

#1380 Neutral naming for apm-agent-dotnet
  README.md
  docker/dotnet/Dockerfile
  docker/opbeans/dotnet/Dockerfile
  scripts/modules/apm_agents.py
  scripts/modules/opbeans.py
  scripts/tests/test_localsetup.py
  scripts/tests/test_service.py
  tests/versions/dotnet.yml
Labels: automation

#1382 apm: Neutral naming for apm-agent-rum-js
  docker/rum/Dockerfile
  scripts/modules/apm_agents.py
  tests/versions/rum.yml
Labels: automation

#1376 apm: Neutral naming for apm-agent-python
  README.md
  scripts/modules/apm_agents.py
  tests/versions/python.yml
Labels: automation

#1414 versions: wrong versions
  scripts/modules/cli.py
Labels: bug
