Repository elastic/apm-integration-testing, pull requests merged in 2022-04, with the labels that each got.

#1464 [automation] Update Elastic stack release version 7.17.2 7.17.3
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency

#1468 Fix: no-kibana flag in managed mode
  scripts/modules/cli.py
  scripts/tests/test_localsetup.py
Labels: bug, Team:Automation, area:dx

#1470 fix bump automation to update cli.py
  .ci/bump-stack-release-version.sh
  scripts/modules/cli.py
Labels: bug, automation, backport

#1472 [automation] Update Elastic stack release version 7.17.2 7.17.3
  scripts/modules/cli.py
Labels: automation, dependency

#1474 [automation] Update Elastic stack release version 8.1.3 8.2.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency
