Repository elastic/apm-integration-testing, pull requests merged in 2023-01, with the labels that each got.

#1545 bump pytest deps to support python3.10
  requirements.txt
Labels: automation, backport

#1546 automation: bump versions and fix automation
  .ci/bump-stack-release-version.sh
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: backport-skip

#1543 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
  .github/workflows/test-reporter.yml
Labels: automation, backport, Team:Automation

#1539 [automation] Update go release version 1.18.9
  docker/apm-server/Dockerfile
Labels: automation, dependency

#1550 automation: bump version for the main branch
  .ci/bump-stack-release-version.sh
  .ci/bump-stack-version.sh
Labels: backport-skip

#1551 [automation] Update Elastic stack release version 8.6.1 8.6.1
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependency
