Repository elastic/apm-integration-testing, pull requests merged in 2023-08, with the labels that each got.

#1569 [updatecli] Bump elastic stack version to 8.8.1/8.10.0
  .ci/scripts/common.sh
  scripts/modules/cli.py
Labels: automation, dependencies, backport-skip

#1570 [updatecli] update elastic stack version for testing 8.10.0-a51cd5d0
  scripts/modules/cli.py
Labels: automation, dependencies, backport-skip

#1571 bump golang version for the APM Server
  docker/apm-server/Dockerfile
Labels: chore, backport-skip

#1572 Pin PyYAML version to 5.3.1 to avoid CI errors temporarily
  requirements.txt
Labels: dependencies, backport-skip

#1573 opbeans-dotnet: use the way to know the agent version
  docker/opbeans/dotnet/run.sh
Labels: dependencies, backport-skip
